'EOF'
server {

	listen 80;
	server_name Your_server_name;
	listen 443 ssl;

	ssl_certificate /etc/letsencrypt/live/Your_server_name/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/Your_server_name/privkey.pem;

	root /var/www/mysite;
	index index.html;


	sub_filter '{{SERVER_IP}}' '$server_addr';
	sub_filter_once on;
	sub_filter_types text/html;
}

server {
	listen 80;
	server_name Your_server_name;
	return 301 hhtps://$host$request_uri;
}

EOF